# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_listener/TimeTransform.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg

class TimeTransform(genpy.Message):
  _md5sum = "b05693e338e8c00beb115d4348be07e1"
  _type = "my_listener/TimeTransform"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Transform geo_trans
time t1
time t2

================================================================================
MSG: geometry_msgs/Transform
# This represents the transform between two coordinate frames in free space.

Vector3 translation
Quaternion rotation

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['geo_trans','t1','t2']
  _slot_types = ['geometry_msgs/Transform','time','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       geo_trans,t1,t2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TimeTransform, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.geo_trans is None:
        self.geo_trans = geometry_msgs.msg.Transform()
      if self.t1 is None:
        self.t1 = genpy.Time()
      if self.t2 is None:
        self.t2 = genpy.Time()
    else:
      self.geo_trans = geometry_msgs.msg.Transform()
      self.t1 = genpy.Time()
      self.t2 = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d4I().pack(_x.geo_trans.translation.x, _x.geo_trans.translation.y, _x.geo_trans.translation.z, _x.geo_trans.rotation.x, _x.geo_trans.rotation.y, _x.geo_trans.rotation.z, _x.geo_trans.rotation.w, _x.t1.secs, _x.t1.nsecs, _x.t2.secs, _x.t2.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.geo_trans is None:
        self.geo_trans = geometry_msgs.msg.Transform()
      if self.t1 is None:
        self.t1 = genpy.Time()
      if self.t2 is None:
        self.t2 = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.geo_trans.translation.x, _x.geo_trans.translation.y, _x.geo_trans.translation.z, _x.geo_trans.rotation.x, _x.geo_trans.rotation.y, _x.geo_trans.rotation.z, _x.geo_trans.rotation.w, _x.t1.secs, _x.t1.nsecs, _x.t2.secs, _x.t2.nsecs,) = _get_struct_7d4I().unpack(str[start:end])
      self.t1.canon()
      self.t2.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d4I().pack(_x.geo_trans.translation.x, _x.geo_trans.translation.y, _x.geo_trans.translation.z, _x.geo_trans.rotation.x, _x.geo_trans.rotation.y, _x.geo_trans.rotation.z, _x.geo_trans.rotation.w, _x.t1.secs, _x.t1.nsecs, _x.t2.secs, _x.t2.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.geo_trans is None:
        self.geo_trans = geometry_msgs.msg.Transform()
      if self.t1 is None:
        self.t1 = genpy.Time()
      if self.t2 is None:
        self.t2 = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.geo_trans.translation.x, _x.geo_trans.translation.y, _x.geo_trans.translation.z, _x.geo_trans.rotation.x, _x.geo_trans.rotation.y, _x.geo_trans.rotation.z, _x.geo_trans.rotation.w, _x.t1.secs, _x.t1.nsecs, _x.t2.secs, _x.t2.nsecs,) = _get_struct_7d4I().unpack(str[start:end])
      self.t1.canon()
      self.t2.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d4I = None
def _get_struct_7d4I():
    global _struct_7d4I
    if _struct_7d4I is None:
        _struct_7d4I = struct.Struct("<7d4I")
    return _struct_7d4I
